version: "3"

services:
  minio:
    command: "server /data"
    environment:
     - MINIO_ACCESS_KEY=example-access-key
     - MINIO_SECRET_KEY=example-secret-key
    image: minio/minio
    restart: always

  redis:
    image: redis
    restart: always
    volumes:
      - data-redis:/data

  db:
    command: ["--wiredTigerCacheSizeGB", "2"]
    environment:
     - MONGO_INITDB_ROOT_USERNAME=root
     - MONGO_INITDB_ROOT_PASSWORD=root
    image: mongo
    restart: always
    volumes:
     - data-mongodb:/data/db

  autoreporter:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file: .env
    volumes:
      # Because the options parsing (which will tell us which previous reports directory the
      # user needs) happens inside the container, we don't know what directory to mount before
      # starting the container. This solution is far from perfect - feel free to propose a better
      # one.
      - /:/host-root/:ro
      - ./output/autoreporter/:/opt/output/autoreporter
      - ./docker/karton.ini:/etc/karton/karton.ini
      - "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"
    profiles: ["autoreporter"]  # This will prevent the service from starting by default

  karton-system:
    command: ["--setup-bucket"]
    depends_on: ["db", "redis", "minio"]
    env_file: .env
    image: "certpl/karton-system:v5.2.0"
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]
    restart: always

  karton-logger:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "python3 -m artemis.stdout_logger"
    depends_on: [karton-system]
    env_file: .env
    restart: always
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]

  metrics:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on: [karton-logger]
    env_file: .env
    ports: ["9000:9000"]
    restart: always
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]
    command: "python3 -m artemis.metrics"

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on: [karton-logger]
    env_file: .env
    environment:
     - DASHBOARD_URL=http://127.0.0.1:5001
    ports: ["5000:5000"]
    restart: always
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]

  karton-dashboard:
    depends_on: [karton-logger]
    env_file: .env
    image: certpl/karton-dashboard:v1.5.0
    ports: [5001:5000]
    restart: always
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]

  karton-admin_panel_login_bruter:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "python3 -m artemis.modules.admin_panel_login_bruter"
    depends_on: [karton-logger]
    env_file: .env
    restart: always
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]

  karton-admin_panels_login_bruter-selenium_chrome:
    image: selenium/node-chrome
    shm_size: 2gb
    depends_on:
      - karton-admin_panels_login_bruter-selenium_hub
    environment:
      - SE_EVENT_BUS_HOST=karton-admin_panels_login_bruter-selenium_hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  karton-admin_panels_login_bruter-selenium_hub:
    image: selenium/hub

  karton-classifier:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "python3 -m artemis.modules.classifier"
    depends_on: [karton-logger]
    env_file: .env
    restart: always
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]

  karton-port_scanner:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "python3 -m artemis.modules.port_scanner"
    depends_on: [karton-logger]
    env_file: .env
    restart: always
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]

  karton-robots:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "python3 -m artemis.modules.robots"
    depends_on: [karton-logger]
    env_file: .env
    restart: always
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]

  karton-vcs:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "python3 -m artemis.modules.vcs"
    depends_on: [karton-logger]
    env_file: .env
    restart: always
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]

  karton-crtsh:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "python3 -m artemis.modules.crtsh"
    depends_on: [karton-logger]
    env_file: .env
    restart: always
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]

  karton-gau:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "python3 -m artemis.modules.gau"
    depends_on: [karton-logger]
    env_file: .env
    restart: always
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]

  karton-ip-lookup:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "python3 -m artemis.modules.ip_lookup"
    depends_on: [karton-logger]
    env_file: .env
    restart: always
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]

  karton-reverse-dns:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "python3 -m artemis.modules.reverse_dns_lookup"
    depends_on: [karton-logger]
    env_file: .env
    restart: always
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]

  karton-bruter:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "python3 -m artemis.modules.bruter"
    depends_on: [karton-logger]
    env_file: .env
    restart: always
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]

  karton-directory_index:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "python3 -m artemis.modules.directory_index"
    depends_on: [karton-logger]
    env_file: .env
    restart: always
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]

  karton-identifier:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "python3 -m artemis.modules.webapp_identifier"
    depends_on: [karton-logger]
    env_file: .env
    restart: always
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]

  karton-joomla_scanner:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "python3 -m artemis.modules.joomla_scanner"
    depends_on: [karton-logger]
    env_file: .env
    restart: always
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]

  karton-wp_scanner:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "python3 -m artemis.modules.wp_scanner"
    depends_on: [karton-logger]
    env_file: .env
    restart: always
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]

  karton-dns_scanner:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "python3 -m artemis.modules.dns_scanner"
    depends_on: [karton-logger]
    env_file: .env
    restart: always
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]

  karton-ftp_bruter:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "python3 -m artemis.modules.ftp_bruter"
    depends_on: [karton-logger]
    env_file: .env
    restart: always
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]

  karton-http_service_to_url:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "python3 -m artemis.modules.http_service_to_url"
    depends_on: [karton-logger]
    env_file: .env
    restart: always
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]

  karton-mysql_bruter:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "python3 -m artemis.modules.mysql_bruter"
    depends_on: [karton-logger]
    env_file: .env
    restart: always
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]

  karton-mail_dns_scanner:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "python3 -m artemis.modules.mail_dns_scanner"
    depends_on: [karton-logger]
    env_file: .env
    restart: always
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]

  karton-nuclei:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "python3 -m artemis.modules.nuclei"
    depends_on: [karton-logger]
    env_file: .env
    restart: always
    volumes:
      - "./docker/karton.ini:/etc/karton/karton.ini"
      - "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"
      - data-nuclei-templates:/root/nuclei-templates
      - data-nuclei-config:/root/.config/nuclei

  karton-postman:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "python3 -m artemis.modules.postman"
    depends_on: [karton-logger]
    env_file: .env
    environment:
     - POSTMAN_MAIL_FROM=artemis@example.com
     - POSTMAN_MAIL_TO=artemis@example.com
    restart: always
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]

  karton-postgresql_bruter:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "python3 -m artemis.modules.postgresql_bruter"
    depends_on: [karton-logger]
    env_file: .env
    restart: always
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]

  karton-wordpress_bruter:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "python3 -m artemis.modules.wordpress_bruter"
    depends_on: [karton-logger]
    env_file: .env
    restart: always
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]

  karton-shodan_vulns:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "python3 -m artemis.modules.shodan_vulns"
    depends_on: [karton-logger]
    env_file: .env
    restart: always
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]

  karton-ssh_bruter:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "python3 -m artemis.modules.ssh_bruter"
    depends_on: [karton-logger]
    env_file: .env
    restart: always
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]

  karton-domain_expiration_scanner:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "python3 -m artemis.modules.domain_expiration_scanner"
    depends_on: [ karton-logger ]
    env_file: .env
    restart: always
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]

  test-drupal-easy-password:
    image: drupal:latest
    ports:
      - 80:80
    volumes:
      - ./test/data/drupal_easy_password/settings.php:/opt/drupal/web/sites/default/settings.php:ro
    restart: always

  test-drupal-easy-password-postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_EXTENSIONS: pg_trgm
    volumes:
      - ./test/data/drupal_easy_password/db_extensions:/docker-entrypoint-initdb.d:ro
    restart: always

#  test-joomla-easy-password:
#    image: joomla:php8.2-apache
#    volumes:
#      - joomla-data:/var/www/html
#    environment:
#      JOOMLA_DB_HOST: joomla-mysql:3306
#      JOOMLA_DB_USER: joomla
#      JOOMLA_DB_PASSWORD: password
#
#  test-joomla-easy-password-mysql:
#    image: mysql:5.7
#    volumes:
#      - joomla-mysql-data:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: password
#      MYSQL_USER: joomla
#      MYSQL_PASSWORD: password
#      MYSQL_DATABASE: joomla
#
#  test-django-easy-password:
#    image: python:3.11.4-slim-buster
#    environment:
#      - DJANGO_SUPERUSER_PASSWORD=password
#      - DJANGO_SUPERUSER_USERNAME=djangouser
#      - DJANGO_SUPERUSER_EMAIL=test111111111@exampple.com
#    command: >
#      sh -c "pip install Django &&
#      python3 usr/src/app/manage.py makemigrations &&
#      python3 usr/src/app/manage.py migrate &&
#      python3 usr/src/app/manage.py runserver 0.0.0.0:8000 &&
#      python3 usr/src/app/manage.py loaddata db.json"
#    volumes:
#      - ./test/data/django/:/usr/src/app/
#      - ./requirements.txt:/urs/src/app/requirements.txt
#    env_file:
#      - ./test/data/django/.env.django-sample
#
#  test-django-easy-password-postgres:
#    image: postgres
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    environment:
#      - POSTGRES_USER=django_user
#      - POSTGRES_PASSWORD=django_password
#      - POSTGRES_DB=django_db
#
#  test-single-page-app-easy-password:
#    image: nginx:latest
#    volumes:
#      - ./test/data/single_page/:/usr/share/nginx/html/
#    ports:
#      - 8080:80
#
#  test-symfony-easy-password:
#    build:
#      context: ./test/data/symfony/docker
#    ports:
#      - 9000:9000
#    volumes:
#      - ./test/data/symfony/app:/var/www/symfony_docker
#      - ./test/data/symfony/config/php.ini:/usr/local/etc/php/php.ini
#    depends_on:
#      - symfony-mysql
#
#  test-symfony-easy-password-mysql:
#    image: mysql
#    command: --default-authentication-plugin=mysql_native_password
#    environment:
#      MYSQL_ROOT_PASSWORD: secret
#      MYSQL_DATABASE: symfony_docker
#      MYSQL_USER: symfony
#      MYSQL_PASSWORD: symfony
#    volumes:
#      - ./mysql:/var/lib/mysql

volumes:
  data-mongodb:
  data-redis:
  data-nuclei-templates:
  data-nuclei-config:
